modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   displayURL="https://github.com/emmathemartian/ad-astra-et-ultra"
   #logoFile="etultra.png"
   credits="None (for now)"
   authors="${mod_authors}"
   description='''${mod_description}'''

[[dependencies."${mod_id}"]]
   modId="ad_astra"
   mandatory=true
   versionRange="[${ad_astra_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="create"
   mandatory=false
   versionRange="[${create_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
